### PR TITLE
Changes to match the signal_ynh package

### PR DESCRIPTION
**Pull request by nathanael-h**
## Problem
- I run package check and it failed because of a different checksum
- I saw issue #4 

## Solution
- *Update sha256 source sum*
- *Changes to match the signal_ynh package*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix 
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---

```
Working time for this test: 2 minutes, 9 seconds (15:43:50)

 ============================================
 Tests summary
 ============================================


Package linter:                OK  (3 warnings, 7 possible improvements)
Install (nourl):               OK
Install (multi):               OK
Backup/restore:               fail
Upgrade:                      fail
Upgrade (01514cf0):           fail
Port already used:             OK

Level results
=============
Level 1 (Installable in at least one scenario)    OK
Level 2 (Installable in all scenarios)            OK
Level 3 (Can be upgraded)                        
Level 4 (Can be backup/restored)                 
Level 5 (No linter errors)                        ok 
Level 6 (App is in a community-operated git org)  ok 
Level 7 (Pass all tests + no linter warnings)    
Level 8 (Maintained and long-term good quality)  
Level 9 (Flagged high-quality in app catalog)    

Global level for this application: 2 (Installable in all scenarios)

Global working time for all tests: 12 minutes, 44 seconds (15:43:55)

```

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/REPLACEBYYOURAPP_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by nathanael-h** [comment]
```
 ============================================
 Tests summary
 ============================================


Package linter:                OK  (2 warnings, 5 possible improvements)
Install (nourl):               OK
Install (multi):               OK
Backup/restore:               fail
Upgrade:                       OK
Upgrade (01514cf0):            OK
Port already used:             OK

Level results
=============
Level 1 (Installable in at least one scenario)    OK
Level 2 (Installable in all scenarios)            OK
Level 3 (Can be upgraded)                         OK
Level 4 (Can be backup/restored)                 
Level 5 (No linter errors)                        ok 
Level 6 (App is in a community-operated git org)  ok 
Level 7 (Pass all tests + no linter warnings)    
Level 8 (Maintained and long-term good quality)  
Level 9 (Flagged high-quality in app catalog)    

Global level for this application: 3 (Can be upgraded)

Global working time for all tests: 16 minutes, 34 seconds (23:56:05)
```

**Comment by nathanael-h** [comment]
Error in restore test is {Error: Unable to install synapse: An error occurred inside the app installation script
Info: The operation 
```
Install the 'synapse' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20211202-112200-app_install-synapse' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - Dec 02 11:22:42 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Info: DEBUG - Dec 02 11:22:42 systemd[1]: Reload failed for A high performance web server and a reverse proxy server.'
Info: DEBUG - + echo -e '[Error] Dec 02 11:21:54 systemd[1]: Starting A high performance web server and a reverse proxy server...
Info: DEBUG - Dec 02 11:21:54 systemd[1]: Started A high performance web server and a reverse proxy server.
Info: DEBUG - Dec 02 11:22:42 systemd[1]: Reloading A high performance web server and a reverse proxy server.
Info: DEBUG - Dec 02 11:22:42 nginx[10690]: nginx: [emerg] duplicate location "/.well-known/matrix/client" in /etc/nginx/conf.d/domain.tld.d/synapse_server_name.conf:7
```

Full log : https://paste.yunohost.org/anaqikovuy.coffeescript

**Comment by nathanael-h** [comment]
Packages-check on my computer seems to send false negative. 
All defined tests:
```
 ============================================
 Tests summary
 ============================================


Package linter:                OK  (2 possible improvements)
Install (nourl):               OK
Install (multi):               OK
Backup/restore:                OK
Upgrade:                       OK
Upgrade (01514cf0):            OK
Port already used:            fail

```


Only install and port already used: 

```
 ============================================
 Tests summary
 ============================================


Install (nourl):               OK
Port already used:             OK
```

**Comment by nathanael-h** [comment]
Can someone trigger the ci, or review, or test?

**Comment by nathanael-h** [comment]
Ohoh!! all check are ok :smiley: :fireworks:  :man_dancing: 

```
 ============================================
 Tests summary
 ============================================


Package linter:                OK  (2 possible improvements)
Install (nourl):               OK
Install (multi):               OK
Backup/restore:                OK
Upgrade:                       OK
Upgrade (01514cf0):            OK
Port already used:             OK

Level results
=============
Level 1 (Installable in at least one scenario)    OK
Level 2 (Installable in all scenarios)            OK
Level 3 (Can be upgraded)                         OK
Level 4 (Can be backup/restored)                  OK
Level 5 (No linter errors)                       
Level 6 (App is in a community-operated git org)  ok 
Level 7 (Pass all tests + no linter warnings)    
Level 8 (Maintained and long-term good quality)  
Level 9 (Flagged high-quality in app catalog)    

Global level for this application: 4 (Can be backup/restored)

Global working time for all tests: 24 minutes, 36 seconds (19:03:27)
You can find the complete log of these tests in /home/...
```

**Comment by tituspijean** [comment]
!testme

**Review by tituspijean — APPROVED** [review]
Not tested, but looks good to me. Maybe use the README generator as suggested by the linter. ;)

**Comment by nathanael-h** [comment]
I looked at the README generator, very nice tool :+1: I'll try it, maybe on another PR. I look forward to a review by Gredin67.

**Comment by nathanael-h** [comment]
Can someone merge?

**Pull request merged**
