### PR TITLE
Update to v 0.3.3

### PR DESCRIPTION
**Pull request by nathanael-h**
## Problem
- *outdated*

## Solution
- *Update to v 0.3.3*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_facebook_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by Gredin67** [comment]
trying an upgrade from 0.2.0, I had to upgrade from command line with option -b to deactivate backup (the backup script was not functional at that time). But upgrade failed, I think because of missing HOME variable

```
error: subprocess-exited-with-error
Warning:   × Getting requirements to build wheel did not run successfully.
Warning:   │ exit code: 1
Warning:   ╰─> [22 lines of output]
Warning:       Traceback (most recent call last):
Warning:         File "/opt/yunohost/mautrix_facebook/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
Warning:           main()
Warning:         File "/opt/yunohost/mautrix_facebook/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
Warning:           json_out['return_val'] = hook(**hook_input['kwargs'])
Warning:         File "/opt/yunohost/mautrix_facebook/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
Warning:           return hook(config_settings)
Warning:         File "/tmp/pip-build-env-lnum8cw6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
Warning:           return self._get_build_requires(
Warning:         File "/tmp/pip-build-env-lnum8cw6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
Warning:           self.run_setup()
Warning:         File "/tmp/pip-build-env-lnum8cw6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
Warning:           super(_BuildMetaLegacyBackend,
Warning:         File "/tmp/pip-build-env-lnum8cw6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
Warning:           exec(compile(code, __file__, 'exec'), locals())
Warning:         File "setup.py", line 3, in <module>
Warning:           from mautrix_facebook.get_version import git_tag, git_revision, version, linkified_version
Warning:         File "/tmp/pip-req-build-2wokp78m/mautrix_facebook/get_version.py", line 9, in <module>
Warning:           "HOME": os.environ["HOME"],
Warning:         File "/usr/lib/python3.9/os.py", line 679, in __getitem__
Warning:           raise KeyError(key) from None
Warning:       KeyError: 'HOME'
Warning:       [end of output]
Warning:   note: This error originates from a subprocess, and is likely not a problem with pip.
Warning: error: subprocess-exited-with-error
Warning: × Getting requirements to build wheel did not run successfully.
Warning: │ exit code: 1
Warning: ╰─> See above for output.
Warning: note: This error originates from a subprocess, and is likely not a problem with pip.
Warning: [Error] Upgrade failed.
```

**Comment by nathanael-h** [comment]
> And I think shorter name, and not reading facebook everywhere is better 


LOL !! You make laugh :rofl: 
I changed it because upstream changed it, but in fact I don't really care about this settings. 
https://github.com/mautrix/facebook/blob/c1ec2f23deb7aa204376b38db0a9338422e63264/mautrix_facebook/example-config.yaml#L106
Did it finally work for you ?

**Comment by Gredin67** [comment]
Install worked, but the app service does not want to talk to synapse, although all tokens are good...

```
2022-03-09 10:17:45,616 - synapse.appservice.scheduler - 308 - INFO - as-recoverer-facebookbot-2- Retrying transaction 66158 for AS ID facebookbot
2022-03-09 10:17:45,629 - synapse.appservice.scheduler - 308 - INFO - as-recoverer-telegrambot-2- Retrying transaction 2628 for AS ID telegrambot
2022-03-09 10:17:46,177 - synapse.http.client - 455 - INFO - as-recoverer-85284dadec6e67e7578001af86ec36114140441910057cc575424c23d2650323-2- Error sending request to  PUT http://localhost:9555/transactions/238?access_token=<redacted>: ConnectionRefusedError Connection refused
2022-03-09 10:17:46,177 - synapse.appservice.api - 272 - WARNING - as-recoverer-85284dadec6e67e7578001af86ec36114140441910057cc575424c23d2650323-2- push_bulk to http://localhost:9555/transactions/238 threw exception(ConnectionRefusedError) Connection was refused by other side: 111: Connection refused. args=('Connection refused',)
2022-03-09 10:17:46,179 - synapse.appservice.scheduler - 289 - INFO - as-recoverer-85284dadec6e67e7578001af86ec36114140441910057cc575424c23d2650323-2- Scheduling retries on 85284dadec6e67e7578001af86ec36114140441910057cc575424c23d2650323 in 16.000000s
2022-03-09 10:17:46,229 - synapse.http.client - 455 - INFO - as-recoverer-dd0260597b83cd99e13dbc5ce85ec09ddd442bebd1be4fe5542029448dc9a5c0-2- Error sending request to  PUT http://localhost:9999/transactions/45?access_token=<redacted>: ConnectionRefusedError Connection refused
2022-03-09 10:17:46,230 - synapse.appservice.api - 272 - WARNING - as-recoverer-dd0260597b83cd99e13dbc5ce85ec09ddd442bebd1be4fe5542029448dc9a5c0-2- push_bulk to http://localhost:9999/transactions/45 threw exception(ConnectionRefusedError) Connection was refused by other side: 111: Connection refused. args=('Connection refused',)
2022-03-09 10:17:46,232 - synapse.appservice.scheduler - 289 - INFO - as-recoverer-dd0260597b83cd99e13dbc5ce85ec09ddd442bebd1be4fe5542029448dc9a5c0-2- Scheduling retries on dd0260597b83cd99e13dbc5ce85ec09ddd442bebd1be4fe5542029448dc9a5c0 in 16.000000s
2022-03-09 10:17:46,242 - synapse.http.client - 455 - INFO - as-recoverer-facebookbot-2- Error sending request to  PUT http://localhost:8449/transactions/66158?access_token=<redacted>: ConnectionRefusedError Connection refused
2022-03-09 10:17:46,242 - synapse.appservice.api - 272 - WARNING - as-recoverer-facebookbot-2- push_bulk to http://localhost:8449/transactions/66158 threw exception(ConnectionRefusedError) Connection was refused by other side: 111: Connection refused. args=('Connection refused',)
2022-03-09 10:17:46,245 - synapse.appservice.scheduler - 289 - INFO - as-recoverer-facebookbot-2- Scheduling retries on facebookbot in 16.000000s
```

**Comment by Gredin67** [comment]
!testme 
I had some syntax left in my config and now it works !

**Comment by nathanael-h** [comment]
Cool to know it works! I think we can merge this PR.

**Comment by yalh76** [comment]
Can we merge ?

**Comment by nathanael-h** [comment]
Yes

**Pull request merged**
